/*
 * OOMainFrame.java
 *
 * Created on 9. August 2006, 19:02
 */

package com.bensmann.superswing.ooo;

import com.sun.star.beans.PropertyValue;
import java.beans.PropertyVetoException;

/**
 *
 * @author  rb
 */
public class OOoMainFrame extends javax.swing.JFrame {
    
    /** Creates new form OOMainFrame */
    public OOoMainFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        getContentPane().add(jDesktopPane1);

        jButton1.setText("N");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        PropertyValue[] prop = new PropertyValue[1];
        prop[0] = new PropertyValue();
        prop[0].Name = "ReadOnly";
        prop[0].Value = true;
        prop[0] = new PropertyValue();
        prop[0].Name = "UpdateDocMode";
        prop[0].Value = com.sun.star.document.UpdateDocMode.NO_UPDATE;
        
        ooInternalFrame = new OOoInternalFrame();
        jDesktopPane1.add(ooInternalFrame);
        try {
            ooInternalFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
        ooInternalFrame.loadDocumentFromURL(
                "file:///c:/workspace/netbeans/WestaWAC/src/com/westaflex/resource/WestaWAC.ott",
                prop);
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ooInternalFrame.close();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OOoMainFrame().setVisible(true);
            }
        });
    }
    
    private OOoInternalFrame ooInternalFrame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    
}
