#!/usr/bin/env bash
#
# VentPlan
#
# Copyright (C) 2005-2010 Informationssysteme Ralf Bensmann.
# Copyright (C) 2011-2012 at of coding UG (haftungsbeschränkt).
#
# Alle Rechte vorbehalten. Nutzung unterliegt Lizenzbedingungen.
# All rights reserved. Use is subject to license terms.
#

set -o nounset

# Operating system
OS=$(uname -s)
# Classpath
#for jar in lib/*
#do
#    exclude=0
#    for ex in juh.jar jurt.jar ridl.jar unoil.jar
#    do
#        if [ ${jar} == ${ex} ]; then
#            exclude=1
#            break
#        fi
#    done
#    [ ${exclude} -eq 0 ] && LIB_CLASSPATH="${LIB_CLASSPATH}:${jar}"
#done
# Skip first colon
#LIB_CLASSPATH=$(echo ${LIB_CLASSPATH} | cut -c 2-)
#CLASSPATH="${LIB_CLASSPATH}"
#export CLASSPATH
# Set VTP temporary directory
case "${OS}" in
        Darwin | Linux | *BSD | SunOS)
            VTPTMP=${TMPDIR}
        ;;
esac
[ -z "${VTPTMP}" ] && VTPTMP=tmp
VTPTMP=${VTPTMP}/ventplan
export VTPTMP
mkdir -p ${VTPTMP} 2>/dev/null
#
LOG=${VTPTMP}/VentPlan.log
# Update
mv update/resources/* resources 2>>${LOG} 1>&2
mv update/lib/* lib 2>>${LOG} 1>&2
mv update/sql/* sql 2>>${LOG} 1>&2
rm -rf update 2>>${LOG} 1>&2
# Start
##java -cp "${CLASSPATH}" griffon.swing.SwingApplication 2>>${LOG} 1>&2
java -cp lib/* griffon.swing.SwingApplication 2>>${LOG} 1>&2
# Remove temporary directory
cd ${VTPTMP}
cd ..
rm -rf ventplan
exit 0
