/*
 * AboutPanel.java
 *
 * Created on 23. Juli 2006, 13:02
 */

package com.bensmann.superswing.component;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author  rb
 */
public class AboutPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form AboutPanel
     */
    public AboutPanel() {
        initComponents();
        setIcon(null);
    }
    
    /**
     * Creates new form AboutPanel
     *
     * @param icon 
     * @param versionText 
     * @param copryightText 
     */
    public AboutPanel(Icon icon, String versionText, String copyrightText) {
        
        this();
        
        setIcon(icon);
        setVersionText(versionText);
        setCopyrightText(copyrightText);
        
    }
    
    public void setIcon(Icon icon) {
        
        if (icon == null) {
            icon = new ImageIcon(getClass().getResource(
                    "/com/bensmann/superswing/resource/image/javaduke.gif"));
        }
        
        imageLabel.setText("");
        imageLabel.setIcon(icon);
        
    }
    
    public void setCloseOnClick() {
        
        imageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setVisible(false);
            }
            
        });
        
    }
    
    public void setVersionText(String text) {
        versionLabel.setText(text);
    }
    
    public void setCopyrightText(String text) {
        copyrightLabel.setText(text);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        imageLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        copyrightLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setText("image");
        imageLabel.setPreferredSize(new java.awt.Dimension(400, 300));

        versionLabel.setFont(new java.awt.Font("Tahoma", 3, 12));
        versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionLabel.setText("version");

        copyrightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyrightLabel.setText("copyright");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imageLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
            .add(versionLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
            .add(copyrightLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(imageLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(versionLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(copyrightLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
    
}
