/*
 * LoadProjectInternalFrame.java
 *
 * Created on 26. Juli 2006, 15:45
 */

package com.bensmann.superswing.component;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author  rb
 */
public class LoadFileChooserInternalFrame extends javax.swing.JInternalFrame {
    
    private boolean fileSelected;
    
    /** Creates new form LoadProjectInternalFrame */
    public LoadFileChooserInternalFrame() {
        initComponents();
    }

    public boolean isFileSelected() {
        return fileSelected;
    }

    public JFileChooser getProjektFileChooser() {
        return projektFileChooser;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        projektFileChooser = new javax.swing.JFileChooser();
        
        setTitle("Projekt laden");
        projektFileChooser.setAcceptAllFileFilterUsed(false);
        projektFileChooser.setFileFilter(new FileFilter() {
            
            public boolean accept(File file) {
                
                boolean b = false;
                
                if (file.isDirectory()) {
                    b = true;
                } else if (file.getName().endsWith(".wpx")) {
                    b = true;
                }
                
                return b;
                
            }
            
            public String getDescription() {
                return "WestaWAC Projekt-Dateien";
            }
            
        });
        projektFileChooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        projektFileChooser.setOpaque(true);
        projektFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projektFileChooserActionPerformed(evt);
            }
        });
        
        
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(projektFileChooser, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(projektFileChooser, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void projektFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projektFileChooserActionPerformed
        fileSelected = true;
        dispose();
    }//GEN-LAST:event_projektFileChooserActionPerformed
    
// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser projektFileChooser;
// End of variables declaration//GEN-END:variables
    
}
