/*
 * ShowErrorInternalFrame.java
 *
 * Created on 27. Juli 2006, 09:28
 */

package com.bensmann.superswing.component;

/**
 *
 * @author  rb
 */
public class ShowErrorInternalFrame extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form ShowErrorInternalFrame
     */
    public ShowErrorInternalFrame() {
        initComponents();
    }
    
    /**
     *
     * @param errorTitle
     * @param errorMessage
     */
    public ShowErrorInternalFrame(String errorTitle, String errorMessage) {
        setErrorTitle(errorTitle);
        setErrorMessage(errorMessage);
    }
    
    /**
     *
     * @param title
     */
    public void setErrorTitle(String errorTitle) {
        this.errorTitle = errorTitle;
        setTitle(errorTitle);
    }
    
    /**
     *
     * @param errorMessage
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
        errorMessageLabel.setText(errorMessage);
    }
    
    /**
     *
     * @param prefix
     * @param message
     * @param stackTraceElement
     */
    public void addStackTrace(String prefix, String message, StackTraceElement[] stackTraceElement) {
        
        boolean firstLine = true;
        StringBuffer stackTraceLine = null;
        
        // Show prefix only in first line (mainly "Caused by" will be used here)
        if (prefix != null && firstLine) {
            stackTraceTextArea.append(prefix);
        }
        
        // Show every element of stacktrace
// os 1.4
        StackTraceElement e;
        for (int i = 0; i < stackTraceElement.length; i++) {
            e = stackTraceElement[i];
            
//        for (StackTraceElement e : stackTraceElement) {
//os 1.4
            stackTraceLine = new StringBuffer();
            
            if (!firstLine) {
                stackTraceLine.append("\tat ");
            } else {
                stackTraceLine.append(" ");
            }
            
            stackTraceLine.
                    append(e.getClassName()).
                    append(".").
                    append(e.getMethodName()).
                    append("(").
                    append(e.getFileName()).
                    append(":").
                    append(e.getLineNumber()).
                    append(")");
            
            // Append message if any
            if (firstLine) {
                
                if (message != null) {
                    stackTraceLine.append(": ").append(message);
                }
                
                firstLine = false;
                
            }
            
            stackTraceTextArea.append(stackTraceLine.toString() + "\n");
            
        }
        
    }
    
    /**
     *
     * @param exception
     */
    public void setException(Exception exception) {
        
        Throwable cause = null;
        
        this.exception = exception;
        
        if (errorTitle == null) {
            setErrorTitle("Fehler");
        }
        if (errorMessage == null) {
            setErrorMessage(exception.getMessage());
        }
        addStackTrace(exception.getClass().getName(), exception.getMessage(), exception.getStackTrace());
        
        cause = exception.getCause();
        while (cause != null) {
            addStackTrace("\nCaused by: ", cause.getMessage(), cause.getStackTrace());
            cause = cause.getCause();
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane2 = new javax.swing.JScrollPane();
        errorMessageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stackTraceTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Fehler");
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Message"));
        errorMessageLabel.setLabelFor(jScrollPane1);
        errorMessageLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        errorMessageLabel.setOpaque(true);
        errorMessageLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jScrollPane2.setViewportView(errorMessageLabel);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));
        stackTraceTextArea.setColumns(20);
        stackTraceTextArea.setEditable(false);
        stackTraceTextArea.setLineWrap(true);
        stackTraceTextArea.setRows(5);
        stackTraceTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane1.setViewportView(stackTraceTextArea);

        jButton1.setText("Nicht OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(476, Short.MAX_VALUE)
                .add(jButton1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButton1))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private String errorTitle;
    private String errorMessage;
    private Exception exception;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea stackTraceTextArea;
    // End of variables declaration//GEN-END:variables
    
}
