/*
 * SettingsDialog.java
 *
 * Created on 25. Juni 2007, 16:09
 */
package com.westaflex.dialogs;

import com.bensmann.superswing.component.util.ConversionUtil;
import com.seebass.tools.Tools;
import com.westaflex.component.classes.ContentAware;
import com.westaflex.component.classes.Raum;
import com.westaflex.component.classes.RaumItem;
import com.westaflex.component.classes.Rooms;
import com.westaflex.component.classes.SeeComboBox;
import com.westaflex.swing.BTGP;
import com.westaflex.component.classes.RaumDataProviderSingleton;
import java.awt.Component;
import java.awt.Container;
import java.awt.Frame;
import java.text.NumberFormat;
import java.util.Enumeration;
import java.util.Locale;
import java.util.Vector;
import javax.swing.AbstractButton;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JSpinner;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author  Oliver
 */
public class RaumDialog extends javax.swing.JDialog {

    private Raum raum = null;

    private Rooms raeume = null;

    private Vector<BTGP> buttonGroups = new Vector<BTGP>();

    private boolean result = false;

    private int index = -1;

    public boolean getResult() {
        return result;
    }

    public Rooms getRaeume() {
        return raeume;
    }

    /**
     * Creates new form SettingsDialog 
     */
    public RaumDialog(Frame parent, boolean modal, Rooms raeume, int index) {

        super(parent, modal);
        initComponents();
        Tools.centerComponent(this);

        initContentAwareProps();

        this.raeume = raeume;
        this.index = index;
        raum = raeume.get(this.index);
        tfRaum.setModel(raeume);
        tfRaum.setRowSelectionAllowed(false);
        tfRaum.setColumnSelectionAllowed(false);
        tfRaum.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                System.out.println("row " + e.getSource().toString());
            }

        });
        tfRaum.getColumnModel().getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                System.out.println("col " + e.getSource().toString());
            }

        });
        // für Auswahl der Normbreiten der Türen in der Tabelle über ComboBox
        SeeComboBox sc = new SeeComboBox(
                new javax.swing.DefaultComboBoxModel(
                new Integer[]{610, 735, 860, 985, 1110, 1235, 1485, 1735, 1985}));
        sc.setEditable(true);
        tfTueren.getColumnModel().getColumn(1).setCellEditor(
                new DefaultCellEditor(sc));
        // Auswahl für Tür oder Durchgang
        SeeComboBox sc2 = new SeeComboBox(
                new javax.swing.DefaultComboBoxModel(
                new String[]{"Tür", "Durchgang"}));
        sc2.setEditable(true);
        tfTueren.getColumnModel().getColumn(0).setCellEditor(
                new DefaultCellEditor(sc2));
        readRaum();

        // RBE-20100201
        raumVolumenBerechnung();
        // RBE-20100201
        // TM100308
        jTextField4FocusLost(null);
        // TM100308

    }

    public RaumDialog(Frame parent, Rooms raeume, int index) {
        this(parent, true, raeume, index);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDurchlassZuluft = new com.westaflex.swing.BTGP();
        bgDurchlassAbluft = new com.westaflex.swing.BTGP();
        bgKanalZuluft = new com.westaflex.swing.BTGP();
        bgKanalAbluft = new com.westaflex.swing.BTGP();
        tpRaum = new javax.swing.JTabbedPane();
        pnDetails = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        cbGeschoss = new com.westaflex.swing.CMBX()  ;
        jLabel3 = new javax.swing.JLabel();
        pbBack = new javax.swing.JButton();
        jTextField1 = new com.westaflex.swing.EDTX();
        pbForward = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new com.westaflex.swing.EDTX();
        jButton3 = new javax.swing.JButton();
        javax.swing.JLabel rfRaumtypLabel = new javax.swing.JLabel();
        rfRaumtypCombobox = new com.westaflex.component.classes.SeeComboBox();
        jPanel4 = new javax.swing.JPanel();
        jComboBox2 = new com.westaflex.swing.CMBX();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new com.westaflex.swing.EDTX();
        jLabel8 = new javax.swing.JLabel();
        jSpinner1 = new com.westaflex.swing.SPIN();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jTextField5 = new com.westaflex.swing.EDTX();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField8 = new com.westaflex.swing.EDTX();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField9 = new com.westaflex.swing.EDTX();
        jLabel30 = new javax.swing.JLabel();
        jTextField6 = new com.westaflex.swing.EDTX();
        jTextField7 = new com.westaflex.swing.EDTX();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfTueren = new com.westaflex.swing.TuerTable();
        jLabel1 = new javax.swing.JLabel();
        tfSpalthoeheTextField = new com.westaflex.swing.EDTX();
        pbRemoveTuer = new javax.swing.JButton();
        pnZusammenfassung = new javax.swing.JPanel();
        spRaum = new javax.swing.JScrollPane();
        tfRaum = new com.westaflex.component.classes.RaumTabelle();
        pbOK = new javax.swing.JButton();
        pbCancel = new javax.swing.JButton();

        buttonGroups.add(bgDurchlassZuluft);
        bgDurchlassZuluft.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.DURCHLASSPOSITION_ZULUFT ).getColumnName());

        buttonGroups.add(bgDurchlassAbluft);
        bgDurchlassAbluft.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.DURCHLASSPOSITION_ABLUFT ).getColumnName());

        buttonGroups.add(bgKanalZuluft);
        bgKanalZuluft.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.KANALANSCHLUSS_ZULUFT ).getColumnName());

        buttonGroups.add(bgKanalAbluft);
        bgKanalAbluft.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.KANALANSCHLUSS_ABLUFT ).getColumnName());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Einstellungen");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Raum"));

        jLabel2.setDisplayedMnemonic('G');
        jLabel2.setText("Geschoss");

        cbGeschoss.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KG", "EG", "OG", "DG", "SB" }));
        cbGeschoss.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.GESCHOSS ).getColumnName());

        jLabel3.setText("Raumnummer");

        pbBack.setText("<");
        pbBack.setMargin(new java.awt.Insets(2, 2, 2, 2));
        pbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbBackActionPerformed(evt);
            }
        });

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("000");
        jTextField1.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.RAUMNUMMER ).getColumnName());
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        pbForward.setText(">");
        pbForward.setMargin(new java.awt.Insets(2, 2, 2, 2));
        pbForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbForwardActionPerformed(evt);
            }
        });

        jLabel4.setText("Raumname");

        jTextField2.setText("Esszimmer");
        jTextField2.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.RAUMNAME ).getColumnName());

        jButton3.setText("...");

        rfRaumtypLabel.setDisplayedMnemonic('B');
        rfRaumtypLabel.setText("Raumtyp");

        rfRaumtypCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Wohnzimmer", "Kinderzimmer", "Schlafzimmer", "Esszimmer", "Arbeitszimmer", "Gästezimmer", "Hausarbeitsraum", "Kellerraum", "WC", "Küche, Kochnische", "Bad mit/ohne WC", "Duschraum", "Sauna", "Flur", "Diele" }));
        rfRaumtypCombobox.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.RAUMTYP ).getColumnName());
        rfRaumtypCombobox.setName("rfRaumtypCombobox"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbGeschoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(pbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbForward, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rfRaumtypLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rfRaumtypCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(rfRaumtypLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbGeschoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pbForward)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rfRaumtypCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Luftart"));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ZU", "AB", "ZU/AB", "ÜB" }));
        jComboBox2.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.LUFTART ).getColumnName());

        jLabel7.setText("Faktor Zuluftverteilung");

        jTextField4.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.VORGABELUFTMENGE ).getColumnName());
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });

        jLabel8.setText("<html>Abluftvolumenstrom in m<sup>3</sup>/h");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(0.1f)));
        jSpinner1.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.FAKTOR_ZULUFTVERTEILUNG ).getColumnName());
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(375, 375, 375))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Durchlassposition"));

        bgDurchlassAbluft.add(jRadioButton5);
        jRadioButton5.setText("Decke");

        bgDurchlassAbluft.add(jRadioButton6);
        jRadioButton6.setText("Wand oben");

        bgDurchlassAbluft.add(jRadioButton7);
        jRadioButton7.setText("Wand unten");

        bgDurchlassAbluft.add(jRadioButton8);
        jRadioButton8.setText("Boden");

        jLabel9.setText("Zuluft");

        jLabel10.setText("Abluft");

        bgDurchlassZuluft.add(jRadioButton9);
        jRadioButton9.setText("Decke");

        bgDurchlassZuluft.add(jRadioButton10);
        jRadioButton10.setText("Wand oben");

        bgDurchlassZuluft.add(jRadioButton11);
        jRadioButton11.setText("Wand unten");

        bgDurchlassZuluft.add(jRadioButton12);
        jRadioButton12.setText("Boden");

        jButton4.setText("Info...");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton9)
                    .addComponent(jLabel9)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jRadioButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE)
                        .addComponent(jRadioButton6, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(jRadioButton7, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(jRadioButton8, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel10))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadioButton10, jRadioButton11, jRadioButton12, jRadioButton9});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadioButton9)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton4))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton12))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton8)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Optional"));

        jTextField5.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.RAUMLAENGE ).getColumnName());
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });

        jLabel21.setText("m");

        jLabel22.setText("Raumlänge");

        jLabel23.setText("Raumfläche");

        jLabel24.setText("<html>m<sup>2</sup>");

        jLabel25.setText("Raumhöhe");

        jLabel26.setText("m");

        jLabel27.setText("Raumbreite");

        jTextField8.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.RAUMBREITE ).getColumnName());
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });

        jLabel28.setText("m");

        jLabel29.setText("Raumvolumen");

        jTextField9.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.RAUMVOLUMEN ).getColumnName());

        jLabel30.setText("<html>m<sup>3</sup>");

        jTextField6.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.RAUMFLAECHE ).getColumnName());
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });

        jTextField7.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.RAUMHOEHE ).getColumnName());
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel26)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel22, jLabel23, jLabel25});

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField5, jTextField6, jTextField7});

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel27, jLabel29});

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel21, jLabel24, jLabel26});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel27)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(jLabel25)
                        .addComponent(jLabel26)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Kanalanschluss"));

        bgKanalAbluft.add(jRadioButton13);
        jRadioButton13.setText("Decke gleiche Ebene");

        bgKanalAbluft.add(jRadioButton14);
        jRadioButton14.setText("Boden gleiche Ebene");

        bgKanalAbluft.add(jRadioButton15);
        jRadioButton15.setText("Boden nächste Ebene");

        bgKanalAbluft.add(jRadioButton16);
        jRadioButton16.setText("Decke vorherige Ebene");

        jLabel15.setText("Zuluft");

        jLabel16.setText("Abluft");

        bgKanalZuluft.add(jRadioButton17);
        jRadioButton17.setText("Decke gleiche Ebene");

        bgKanalZuluft.add(jRadioButton18);
        jRadioButton18.setText("Boden gleiche Ebene");

        bgKanalZuluft.add(jRadioButton19);
        jRadioButton19.setText("Boden nächste Ebene");

        bgKanalZuluft.add(jRadioButton20);
        jRadioButton20.setText("Decke vorherige Ebene");

        jButton5.setText("Info...");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addGap(55, 55, 55)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton20)
                    .addComponent(jRadioButton18)
                    .addComponent(jRadioButton17)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(69, 69, 69))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jRadioButton16, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(jRadioButton15, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(jRadioButton14, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(jRadioButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE)))
                .addGap(94, 94, 94))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadioButton17, jRadioButton18, jRadioButton19, jRadioButton20});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton17))
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton14)
                            .addComponent(jRadioButton18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton19)
                            .addComponent(jRadioButton15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton16)
                            .addComponent(jRadioButton20))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tfTueren.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, new Boolean(true)},
                {"", null, null, null, new Boolean(true)},
                {"", null, null, null, new Boolean(true)},
                {"", null, null, null, new Boolean(true)},
                {"", null, null, null, new Boolean(true)},
                {"", null, null, null, new Boolean(true)}
            },
            new String [] {
                "Bezeichnung", "Breite in mm", "Querschnittsfläche in mm²", "Spaltenhöhe in mm", "mit Dichtung"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tfTueren.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.TUEREN ).getColumnName());
        tfTueren.setFillsViewportHeight(true);
        tfTueren.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jScrollPane1.setViewportView(tfTueren);

        jLabel1.setText("Maximale Türspalthöhe [mm]");

        tfSpalthoeheTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfSpalthoeheTextField.setText("10.0");
        tfSpalthoeheTextField.setToolTipText(RaumDataProviderSingleton.getInstance().getRaumItemByProp( RaumItem.PROP.MAX_TUERSPALTHOEHE ).getColumnName());
        tfSpalthoeheTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSpalthoeheTextFieldFocusLost(evt);
            }
        });

        pbRemoveTuer.setText("Tür entfernen");
        pbRemoveTuer.setToolTipText("Tür entfernen");
        pbRemoveTuer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbRemoveTuerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDetailsLayout = new javax.swing.GroupLayout(pnDetails);
        pnDetails.setLayout(pnDetailsLayout);
        pnDetailsLayout.setHorizontalGroup(
            pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tfSpalthoeheTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbRemoveTuer))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnDetailsLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnDetailsLayout.setVerticalGroup(
            pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, 0, 142, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfSpalthoeheTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbRemoveTuer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        tpRaum.addTab("Details", pnDetails);

        pnZusammenfassung.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnZusammenfassungComponentShown(evt);
            }
        });

        spRaum.setBackground(new java.awt.Color(255, 255, 255));

        tfRaum.setIntercellSpacing(new java.awt.Dimension(2, 2));
        tfRaum.setRowHeight(20);
        tfRaum.getTableHeader().setReorderingAllowed(false);
        spRaum.setViewportView(tfRaum);

        javax.swing.GroupLayout pnZusammenfassungLayout = new javax.swing.GroupLayout(pnZusammenfassung);
        pnZusammenfassung.setLayout(pnZusammenfassungLayout);
        pnZusammenfassungLayout.setHorizontalGroup(
            pnZusammenfassungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnZusammenfassungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spRaum, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnZusammenfassungLayout.setVerticalGroup(
            pnZusammenfassungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnZusammenfassungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spRaum, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpRaum.addTab("Zusammenfassung", pnZusammenfassung);

        pbOK.setText("OK");
        pbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbOKActionPerformed(evt);
            }
        });

        pbCancel.setText("Abbrechen");
        pbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpRaum, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pbOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbCancel)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pbCancel, pbOK});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpRaum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbCancel)
                    .addComponent(pbOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initContentAwareProps() {
        // jPanel3: Raum
        NumberFormat nf = NumberFormat.getInstance(Locale.GERMANY);
        nf.setGroupingUsed(true);
        nf.setMinimumFractionDigits(2);

        cbGeschoss.setRaumItemProp(RaumItem.PROP.GESCHOSS);
        rfRaumtypCombobox.setRaumItemProp(RaumItem.PROP.RAUMTYP);
        jTextField1.setRaumItemProp(RaumItem.PROP.RAUMNUMMER);
        jTextField2.setRaumItemProp(RaumItem.PROP.RAUMNAME);

        // jPanel4: Luftart
        jComboBox2.setRaumItemProp(RaumItem.PROP.LUFTART);
        jSpinner1.setRaumItemProp(RaumItem.PROP.FAKTOR_ZULUFTVERTEILUNG);
        jTextField4.setRaumItemProp(RaumItem.PROP.VORGABELUFTMENGE);

        // jPanel5: Duchlassposition
        bgDurchlassZuluft.setRaumItemProp(RaumItem.PROP.DURCHLASSPOSITION_ZULUFT);
        bgDurchlassAbluft.setRaumItemProp(RaumItem.PROP.DURCHLASSPOSITION_ABLUFT);

        // jPanel6: Kanalanschluß
        bgKanalZuluft.setRaumItemProp(RaumItem.PROP.KANALANSCHLUSS_ZULUFT);
        bgKanalAbluft.setRaumItemProp(RaumItem.PROP.KANALANSCHLUSS_ABLUFT);

        rfRaumtypCombobox.setRaumItemProp(RaumItem.PROP.RAUMTYP);



        jTextField5.setRaumItemProp(RaumItem.PROP.RAUMLAENGE);
        jTextField8.setRaumItemProp(RaumItem.PROP.RAUMBREITE);
        jTextField9.setRaumItemProp(RaumItem.PROP.RAUMVOLUMEN);
        jTextField6.setRaumItemProp(RaumItem.PROP.RAUMFLAECHE);
        jTextField7.setRaumItemProp(RaumItem.PROP.RAUMHOEHE);
        tfTueren.setRaumItemProp(RaumItem.PROP.TUEREN);
        tfSpalthoeheTextField.setRaumItemProp(RaumItem.PROP.MAX_TUERSPALTHOEHE);
    }

    private void pbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbCancelActionPerformed
        result = false;
        ((JButton) evt.getSource()).getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_pbCancelActionPerformed

    private void pbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbOKActionPerformed
        writeRaum();
        result = true;
        ((JButton) evt.getSource()).getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_pbOKActionPerformed

    private void pnZusammenfassungComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnZusammenfassungComponentShown

        writeRaum();
//        tfRaum.setModel(new DefaultTableModel(raum.getData(), new Object[]{"<html><h1>Name", "<html><h1>Wert"}));
        tfRaum.setModel(raeume);
    }//GEN-LAST:event_pnZusammenfassungComponentShown

private void pbForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbForwardActionPerformed
    writeRaum();
    if (index < raeume.getRowCount() - 1) {
        index += 1;
        raum = raeume.get(index);
        readRaum();
    }
}//GEN-LAST:event_pbForwardActionPerformed

private void pbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbBackActionPerformed
    writeRaum();
    if (index > 0) {
        index -= 1;
        raum = raeume.get(index);

        readRaum();
    }
}//GEN-LAST:event_pbBackActionPerformed

private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged

    float fFaktorZuluft = 0f;
    String sRaumtyp = (String) raum.getRaumItemValue(RaumItem.PROP.RAUMTYP);
    if (sRaumtyp.contains("Wohn")) {
        fFaktorZuluft = 3f;
    } else if (sRaumtyp.contains("Kind") || sRaumtyp.contains("Schlaf")) {
        fFaktorZuluft = 2f;
    } else if (sRaumtyp.contains("Ess") || sRaumtyp.contains("Arbeit") || sRaumtyp.contains("Gäste")) {
        fFaktorZuluft = 1.5f;
    } else if (raum.getRaumItemValue(RaumItem.PROP.LUFTART).equals("ZU/AB")) {
        fFaktorZuluft = (Float) raum.getRaumItemValue(RaumItem.PROP.FAKTOR_ZULUFTVERTEILUNG);
    }
    if (sRaumtyp.contains("Schlaf") || sRaumtyp.contains("Kind")) {
        if ((Float) ((JSpinner) evt.getSource()).getValue() > fFaktorZuluft + 1.0f) {
            jSpinner1.setValue(fFaktorZuluft + 1.0f);
        } else if ((Float) ((JSpinner) evt.getSource()).getValue() < fFaktorZuluft - 1.0f) {
            jSpinner1.setValue(fFaktorZuluft - 1.0f);
        }
    } else {
        if ((Float) ((JSpinner) evt.getSource()).getValue() > fFaktorZuluft + 0.5f) {
            jSpinner1.setValue(fFaktorZuluft + 0.5f);
        } else if ((Float) ((JSpinner) evt.getSource()).getValue() < fFaktorZuluft - 0.5f) {
            jSpinner1.setValue(fFaktorZuluft - 0.5f);
        }
    }

}//GEN-LAST:event_jSpinner1StateChanged

private void pbRemoveTuerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbRemoveTuerActionPerformed
    // markierte Tür entfernen
    int row = tfTueren.getSelectedRow();
    raeume.get(index).getTueren().remove(row);
    readRaum();
}//GEN-LAST:event_pbRemoveTuerActionPerformed

private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
    raumVolumenBerechnung();
}//GEN-LAST:event_jTextField6FocusLost

private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
    raumVolumenBerechnung();
}//GEN-LAST:event_jTextField5FocusLost

private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost
    raumVolumenBerechnung();
}//GEN-LAST:event_jTextField8FocusLost

private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
    raumVolumenBerechnung();
}//GEN-LAST:event_jTextField7FocusLost

private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
    NumberFormat nf = NumberFormat.getInstance(Locale.GERMANY);
    nf.setGroupingUsed(true);
    nf.setMinimumFractionDigits(2);
    float fLuftmenge = ConversionUtil.parseFloatFromComponent(jTextField4);
    jTextField4.setText(nf.format(fLuftmenge));
}//GEN-LAST:event_jTextField4FocusLost

private void tfSpalthoeheTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSpalthoeheTextFieldFocusLost
    NumberFormat nf = NumberFormat.getInstance(Locale.UK);
    nf.setGroupingUsed(true);
    nf.setMinimumFractionDigits(2);
    float fSpalthoehe = ConversionUtil.parseFloatFromComponent(tfSpalthoeheTextField);
    tfSpalthoeheTextField.setText(nf.format(fSpalthoehe));
}//GEN-LAST:event_tfSpalthoeheTextFieldFocusLost

    private void raumVolumenBerechnung() {

        NumberFormat nf = NumberFormat.getInstance(Locale.GERMANY);
        nf.setGroupingUsed(true);
        nf.setMinimumFractionDigits(2);
        float fLaenge = 0f, fBreite = 0f, fHoehe = 0f, fFlaeche = 0f;
        if (!jTextField5.getText().isEmpty()) {
            fLaenge = ConversionUtil.parseFloatFromComponent(jTextField5);
        }
        if (!jTextField8.getText().isEmpty()) {
            fBreite = ConversionUtil.parseFloatFromComponent(jTextField8);
        }
        if (!jTextField7.getText().isEmpty()) {
            fHoehe = ConversionUtil.parseFloatFromComponent(jTextField7);
        }
        if (!jTextField6.getText().isEmpty()) {
            fFlaeche = ConversionUtil.parseFloatFromComponent(jTextField6);
        }
        float fVolumen = 0f;

        if (0.0 != fLaenge && 0.0 != fBreite) {
            fFlaeche = round2(fLaenge * fBreite);
            raum.setRaumItemValue(RaumItem.PROP.RAUMFLAECHE, fFlaeche);
            jTextField6.setText(nf.format(fFlaeche));
            jTextField5.setText(nf.format(fLaenge));
            jTextField8.setText(nf.format(fBreite));
            if (0 != fFlaeche && 0 != fHoehe) {
                fVolumen = round2(fFlaeche * fHoehe);
                raum.setRaumItemValue(RaumItem.PROP.RAUMVOLUMEN, fVolumen);
                jTextField9.setText(nf.format(fVolumen));
                jTextField7.setText(nf.format(fHoehe));
            }
        }
        if (0 != fFlaeche && 0 != fHoehe) {
            fVolumen = round2(fFlaeche * fHoehe);
            raum.setRaumItemValue(RaumItem.PROP.RAUMVOLUMEN, fVolumen);
            jTextField9.setText(nf.format(fVolumen));
            jTextField7.setText(nf.format(fHoehe));
            jTextField6.setText(nf.format(fFlaeche));
        }
    }

    private float round2(float f) {
        return Math.round(f * 100) / 100f;
    }

    /**
     * syncs room with dialogitems
     * @param read if true, dialogitems are set according to roomvalues
     * if false room is updated
     *
     */
    private void writeRaum() {

        raumVolumenBerechnung();
        // TM100308
        jTextField4FocusLost(null);
        // TM100308
        retrieveComponents(pnDetails, true);
        retrieveButtonGroups(true);
    }

    private void readRaum() {

        retrieveComponents(pnDetails, false);
        retrieveButtonGroups(false);
    }

    private void retrieveComponents(Container cont, boolean set) {

        Component[] myComp = null;

        if (cont instanceof ContentAware) {
            //String key = ((JComponent) cont).getToolTipText();
            RaumItem.PROP prop = ((ContentAware) cont).getRaumItemProp();
            if (set == true) {
                raum.setRaumItemValue(prop, ((ContentAware) cont).getValue());
            } else {
                ((ContentAware) cont).setValue(raum.getRaumItemValue(prop));
            }

        }
        myComp = cont.getComponents();
        for (Component comp : myComp) {
            retrieveComponents((Container) comp, set);
        }

    }

    private void retrieveButtonGroups(boolean set) {
        for (BTGP cont : buttonGroups) {
            RaumItem.PROP prop = ((ContentAware) cont).getRaumItemProp();
            if (set == true) {
                raum.setRaumItemValue(prop, cont.getString());
            } else {
                cont.setValue(raum.getRaumItemValue(prop));
            }
            Enumeration<AbstractButton> e = cont.getElements();
            while (e.hasMoreElements()) {
                if (raum.getRaumItemValue(RaumItem.PROP.LUFTART).equals("ZU/AB")) {
                    jSpinner1.setEnabled(true);
                    jTextField4.setEnabled(true);
                    e.nextElement().setEnabled(true);
                } else if (raum.getRaumItemValue(RaumItem.PROP.LUFTART).equals("ZU")) {
                    jSpinner1.setEnabled(true);
                    jTextField4.setEnabled(false);
                    if (prop.equals(RaumItem.PROP.DURCHLASSPOSITION_ZULUFT)
                            || prop.equals(RaumItem.PROP.KANALANSCHLUSS_ZULUFT)) {
                        e.nextElement().setEnabled(true);
                    } else {
                        e.nextElement().setEnabled(false);
                    }
                } else if (raum.getRaumItemValue(RaumItem.PROP.LUFTART).equals("AB")) {
                    jSpinner1.setEnabled(false);
                    jTextField4.setEnabled(true);
                    if (prop.equals(RaumItem.PROP.DURCHLASSPOSITION_ABLUFT)
                            || prop.equals(RaumItem.PROP.KANALANSCHLUSS_ABLUFT)) {
                        e.nextElement().setEnabled(true);
                    } else {
                        e.nextElement().setEnabled(false);
                    }
                } else if (raum.getRaumItemValue(RaumItem.PROP.LUFTART).equals("ÜB")) {
                    jSpinner1.setEnabled(false);
                    jTextField4.setEnabled(false);
                    e.nextElement().setEnabled(false);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.westaflex.swing.BTGP bgDurchlassAbluft;
    private com.westaflex.swing.BTGP bgDurchlassZuluft;
    private com.westaflex.swing.BTGP bgKanalAbluft;
    private com.westaflex.swing.BTGP bgKanalZuluft;
    private com.westaflex.swing.CMBX cbGeschoss;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.westaflex.swing.CMBX jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.westaflex.swing.SPIN jSpinner1;
    private com.westaflex.swing.EDTX jTextField1;
    private com.westaflex.swing.EDTX jTextField2;
    private com.westaflex.swing.EDTX jTextField4;
    private com.westaflex.swing.EDTX jTextField5;
    private com.westaflex.swing.EDTX jTextField6;
    private com.westaflex.swing.EDTX jTextField7;
    private com.westaflex.swing.EDTX jTextField8;
    private com.westaflex.swing.EDTX jTextField9;
    private javax.swing.JButton pbBack;
    private javax.swing.JButton pbCancel;
    private javax.swing.JButton pbForward;
    private javax.swing.JButton pbOK;
    private javax.swing.JButton pbRemoveTuer;
    private javax.swing.JPanel pnDetails;
    private javax.swing.JPanel pnZusammenfassung;
    private com.westaflex.component.classes.SeeComboBox rfRaumtypCombobox;
    private javax.swing.JScrollPane spRaum;
    private com.westaflex.component.classes.RaumTabelle tfRaum;
    private com.westaflex.swing.EDTX tfSpalthoeheTextField;
    private com.westaflex.swing.TuerTable tfTueren;
    private javax.swing.JTabbedPane tpRaum;
    // End of variables declaration//GEN-END:variables
}
