/*
 * SettingsDialog.java
 *
 * Created on 25. Juni 2007, 16:09
 */
package com.westaflex.dialogs;

import com.seebass.tools.Tools;
import com.seebass.tools.SeeXML;
import com.westaflex.resource.Strings.Strings;
import java.awt.Component;
import java.awt.Frame;
import java.io.File;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathExpression;
import javax.xml.xpath.XPathExpressionException;
import javax.xml.xpath.XPathFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author  Oliver
 */
public class SettingsDialog extends javax.swing.JDialog {

    /** Creates new form SettingsDialog */
    public SettingsDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        provideFieldContent(false);
        Tools.centerComponent(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpSettings = new javax.swing.JTabbedPane();
        pnUserData = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etFirma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        etVorname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        etNachname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        etKuerzel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        etStrasse = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        etPLZ = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        etOrt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        etTitel = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        etPosition = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        etFax = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        etTelefon = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        etTelefon1 = new javax.swing.JTextField();
        pbOK = new javax.swing.JButton();
        pbCancel = new javax.swing.JButton();

        setTitle("Einstellungen");

        pnUserData.setName("UserProfile.xcu"); // NOI18N

        jLabel1.setText("Firma");

        etFirma.setName("o"); // NOI18N

        jLabel2.setText("Vorname");

        etVorname.setName("givenname"); // NOI18N

        jLabel3.setText("Nachname");

        etNachname.setName("sn"); // NOI18N

        jLabel4.setText("Kürzel");

        etKuerzel.setName("initials"); // NOI18N

        jLabel5.setText("Straße");

        etStrasse.setName("street"); // NOI18N

        jLabel6.setText("PLZ");

        etPLZ.setName("postalcode"); // NOI18N

        jLabel7.setText("Ort");

        etOrt.setName("l"); // NOI18N

        jLabel8.setText("Titel");

        etTitel.setName("title"); // NOI18N

        jTextField9.setName("position"); // NOI18N

        etPosition.setText("Position");

        jLabel10.setText("Fax");

        etFax.setName("facsimiletelephonenumber"); // NOI18N

        jLabel11.setText("Tel.");

        etTelefon.setName("telephonenumber"); // NOI18N

        jLabel12.setText("E-Mail");

        etTelefon1.setName("mail"); // NOI18N

        javax.swing.GroupLayout pnUserDataLayout = new javax.swing.GroupLayout(pnUserData);
        pnUserData.setLayout(pnUserDataLayout);
        pnUserDataLayout.setHorizontalGroup(
            pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(pnUserDataLayout.createSequentialGroup()
                        .addGroup(pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etTelefon1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                            .addGroup(pnUserDataLayout.createSequentialGroup()
                                .addGroup(pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnUserDataLayout.createSequentialGroup()
                                        .addGroup(pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(etTelefon)
                                            .addComponent(etTitel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                        .addGroup(pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnUserDataLayout.createSequentialGroup()
                                                .addComponent(etPosition)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(pnUserDataLayout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(23, 23, 23)))
                                        .addGroup(pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(etFax)
                                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                                    .addGroup(pnUserDataLayout.createSequentialGroup()
                                        .addComponent(etPLZ, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(etOrt, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnUserDataLayout.createSequentialGroup()
                                        .addComponent(etVorname, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(etNachname, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(etKuerzel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(etFirma, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                                    .addComponent(etStrasse, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGap(6, 6, 6))
        );

        pnUserDataLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {etNachname, etVorname});

        pnUserDataLayout.setVerticalGroup(
            pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(etFirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(etVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etNachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(etKuerzel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(etStrasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(etPLZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(etPosition)
                    .addComponent(etTitel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(etTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(etFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnUserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(etTelefon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tpSettings.addTab("Benutzerdaten", pnUserData);

        pbOK.setText("OK");
        pbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbOKActionPerformed(evt);
            }
        });

        pbCancel.setText("Abbrechen");
        pbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(pbOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tpSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pbCancel, pbOK});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pbOK)
                    .addComponent(pbCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void pbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbCancelActionPerformed
        ((JButton) evt.getSource()).getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_pbCancelActionPerformed

    private void pbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbOKActionPerformed
        provideFieldContent(true);
        ((JButton) evt.getSource()).getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_pbOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SettingsDialog(new javax.swing.JFrame(), true).setVisible(true);
            }

        });
    }

    private void provideFieldContent(boolean writeMode) {

        final String userProfileStub = "/user/registry/data/org/openoffice/UserProfile.xcu";
        String userInstall = System.getenv("UserInstallation");
        String s = "";
        if (userInstall != null) {
            try {
                URI uri = new URI(userInstall + userProfileStub);
                File f = new File(uri);
                Document doc = null;
                if (!f.exists()) {
                    doc = SeeXML.getInstance().makeNewXMLFile();
                } else {
                    doc = SeeXML.getInstance().openXMLFile(f.getAbsolutePath());
                }
                if (doc != null) {
                    String name = null;
                    XPath xp = XPathFactory.newInstance().newXPath();
                    XPathExpression x = null;
                    Node rootNode = null;
                    for (Component c : pnUserData.getComponents()) {
                        name = c.getName();
                        if (name != null) {
                            try {
                                if (rootNode == null) {
                                    x = xp.compile("/component-data/node[@name=\"Data\"]");
                                    rootNode = (Node) x.evaluate(doc, XPathConstants.NODE);
                                }
                                x = xp.compile("/component-data/node[@name=\"Data\"]/prop[@name=\"" + name + "\"]/value");
                                NodeList nodes = (NodeList) x.evaluate(doc, XPathConstants.NODESET);
                                if (nodes.getLength() == 1) {
                                    if (writeMode == true) {
                                        s = ((JTextField) c).getText();
                                        nodes.item(0).setTextContent(s);
                                    } else {
                                        s = nodes.item(0).getTextContent();
                                        ((JTextField) c).setText(SeeXML.decode(s));
                                    }
                                }
                            } catch (XPathExpressionException ex) {
                                ex.printStackTrace();
                            }
                        }
                    }
                    if (writeMode == true) {
                        SeeXML.getInstance().saveXMLFile(doc, f.getAbsolutePath());
                    }
                } else {
                    Tools.errbox(Strings.NO_USER_INSTALLATION);
                }
            } catch (URISyntaxException ex) {
                Tools.errbox(Strings.NO_USER_INSTALLATION);
                ex.printStackTrace();
            }
        } else {
            Tools.errbox(Strings.NO_USER_INSTALLATION);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField etFax;
    private javax.swing.JTextField etFirma;
    private javax.swing.JTextField etKuerzel;
    private javax.swing.JTextField etNachname;
    private javax.swing.JTextField etOrt;
    private javax.swing.JTextField etPLZ;
    private javax.swing.JLabel etPosition;
    private javax.swing.JTextField etStrasse;
    private javax.swing.JTextField etTelefon;
    private javax.swing.JTextField etTelefon1;
    private javax.swing.JTextField etTitel;
    private javax.swing.JTextField etVorname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton pbCancel;
    private javax.swing.JButton pbOK;
    private javax.swing.JPanel pnUserData;
    private javax.swing.JTabbedPane tpSettings;
    // End of variables declaration//GEN-END:variables
}
