/*
 * SettingsDialog.java
 *
 * Created on 25. Juni 2007, 16:09
 */

package com.westaflex.dialogs;

import com.seebass.tools.Tools;
import java.awt.Frame;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author  Oliver
 */
public class TeilstreckenAuswahl extends javax.swing.JDialog {
    
    private String rc = "";

    /** Creates new form SettingsDialog */
    public TeilstreckenAuswahl(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Tools.centerComponent(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        pbOK = new javax.swing.JButton();
        pbCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        verfgbTeilstreckenScrollPane = new javax.swing.JScrollPane();
        verfgbTeilstreckenList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        hinzufuegenButton = new javax.swing.JButton();
        entfernenButton = new javax.swing.JButton();
        ausgewTeilstreckenScrollPane = new javax.swing.JScrollPane();
        ausgewTeilstreckenList = new javax.swing.JList();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        uebernTeilstreckenTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teilstrecken ausw\u00e4hlen");
        pbOK.setText("OK");
        pbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbOKActionPerformed(evt);
            }
        });

        pbCancel.setText("Abbrechen");
        pbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("<html>Verf\u00fcgbare<br>Teilstrecken</html>");

        verfgbTeilstreckenScrollPane.setViewportView(verfgbTeilstreckenList);

        jLabel2.setText("<html>Ausgew\u00e4hlte<br>Teilstrecken</html>");

        hinzufuegenButton.setText(">>");
        hinzufuegenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hinzufuegenButtonActionPerformed(evt);
            }
        });

        entfernenButton.setText("<<");
        entfernenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entfernenButtonActionPerformed(evt);
            }
        });

        ausgewTeilstreckenScrollPane.setViewportView(ausgewTeilstreckenList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(verfgbTeilstreckenScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hinzufuegenButton)
                    .addComponent(entfernenButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ausgewTeilstreckenScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(hinzufuegenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entfernenButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ausgewTeilstreckenScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verfgbTeilstreckenScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jLabel3.setText("\u00dcbernommen wird:");

        uebernTeilstreckenTextField.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(uebernTeilstreckenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uebernTeilstreckenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pbOK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pbCancel)))
                        .addGap(19, 19, 19))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pbCancel, pbOK});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pbOK)
                    .addComponent(pbCancel))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void entfernenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entfernenButtonActionPerformed
        DefaultListModel model = null;
        Object[] values = ausgewTeilstreckenList.getSelectedValues();
        
        model = (DefaultListModel) ausgewTeilstreckenList.getModel();
        for (int i = 0; i < values.length; i++) {
            model.removeElement(values[i]);
        }
        
        model = (DefaultListModel) verfgbTeilstreckenList.getModel();
        for (int i = 0; i < values.length; i++) {
            model.addElement(values[i]);
        }
        
        updateUebernommeneTeilstrecken();
    }//GEN-LAST:event_entfernenButtonActionPerformed
    
    private void hinzufuegenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hinzufuegenButtonActionPerformed
        DefaultListModel model = null;
        Object[] values = verfgbTeilstreckenList.getSelectedValues();
        
        model = (DefaultListModel) ausgewTeilstreckenList.getModel();
        for (int i = 0; i < values.length; i++) {
            model.addElement(values[i]);
        }
        
        model = (DefaultListModel) verfgbTeilstreckenList.getModel();
        for (int i = 0; i < values.length; i++) {
            model.removeElement(values[i]);
        }
        
        updateUebernommeneTeilstrecken();
    }//GEN-LAST:event_hinzufuegenButtonActionPerformed
    
    private void pbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbCancelActionPerformed
        rc = null;
        dispose();
    }//GEN-LAST:event_pbCancelActionPerformed
    
    private void pbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbOKActionPerformed
        rc = uebernTeilstreckenTextField.getText();
        dispose();
    }//GEN-LAST:event_pbOKActionPerformed
    public String execute(){
        setVisible(true);
        return rc;
    }
    private void updateUebernommeneTeilstrecken() {
        
        ListModel model = null;
        int size = -1;
        StringBuffer sb = new StringBuffer();
        
        uebernTeilstreckenTextField.setText("");
        
        model = ausgewTeilstreckenList.getModel();
        size = model.getSize();
        for (int i = 0; i < size; i++) {
            sb.append(model.getElementAt(i)).append("; ");
        }
        
        uebernTeilstreckenTextField.setText(sb.toString());
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeilstreckenAuswahl(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    public void setTeilstrecken(String[] verfgbTeilstrecken, String[] ausgewTeilstrecken) {
        DefaultListModel model = new DefaultListModel();
        
        for (int i = 0; i < verfgbTeilstrecken.length; i++) {
            model.addElement(verfgbTeilstrecken[i]);
        }
        verfgbTeilstreckenList.setModel(model);
        ausgewTeilstreckenList.setModel(new DefaultListModel());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ausgewTeilstreckenList;
    private javax.swing.JScrollPane ausgewTeilstreckenScrollPane;
    private javax.swing.JButton entfernenButton;
    private javax.swing.JButton hinzufuegenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton pbCancel;
    private javax.swing.JButton pbOK;
    private javax.swing.JTextField uebernTeilstreckenTextField;
    private javax.swing.JList verfgbTeilstreckenList;
    private javax.swing.JScrollPane verfgbTeilstreckenScrollPane;
    // End of variables declaration//GEN-END:variables
}
